os: linux
dist: trusty
language: php

php:
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3

install:
- composer install

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit

cache:
  directories:
  - $HOME/.composer/cache/files
  - vendor
