os: linux
dist: trusty
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit

after_success:
  - if [[ "7.2" == "${TRAVIS_PHP_VERSION}" ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
